spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 30MB
      max-request-size: 30MB
---
#로컬설정
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create
  devtools:
    livereload:
      enabled: true
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
#운영설정
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/DB명?serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:
server:
  port: 5005
logging:
  level:
    root: error
